[workspace]
members = ["axoupdater", "axoupdater-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
homepage = "https://github.com/axodotdev/axoupdater"
repository = "https://github.com/axodotdev/axoupdater"
